#!/bin/bash

#your github id goes here
yourusername="YourGithubId"

#generate a personal token from your github settings
#menu-->personal access token.  Make sure you have
#repo,delete_repo and admin:org checked for your token
token="theAccessTokenFromGithub"

#name of the organization you want repo to go in
organization="YourOrganizationName"

#name of the file that stores info about your team/repo names
#and id.
#each line of file should look like this:
#nameofrepo|githubid|teamid
inputfile="nameOfInputFile"
while IFS="|" read realname githubid teamid
do

    realname=${realname//[[:blank:]]/}
    githubid=${githubid//[[:blank:]]/}
    echo "$realname|$githubid|$teamid"

    #delete repo
    curl -u "$yourusername:$yourtoken" -X DELETE https://api.github.com/repos/$organization/$realname

    #delete teams
    curl -u "$yourusername:$yourtoken" -X DELETE https://api.github.com/teams/$teamid
done < $inputfile
